# Generated by Django 5.0.2 on 2024-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=59)),
                ('discription', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.PositiveBigIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
